version: '3'
services:
  server:
    build: .
    container_name: notion-clone
    volumes:
      - .:/usr/src/app
      # node_modulesはマウント対象から除外
      - /usr/src/app/node_modules/
    ports:
      - 8080:8080
    command: npm start

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=notion-clone
    volumes:
      - ../db:/data/db
    ports:
      - 27017:27017

  mongo_express:
    image: mongo-express
    restart: always
    container_name: mongo_express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo


